### ISSUE TITLE
rendering doesnt starts...

### ISSUE THREAD

**Issue by CamillaLee** [unhappychoice/ReplayMod#16]
every time when I try to start to render the game stop like this forever...
no matter how long I wait the number wouldnt change and when I click anywhere it says the game doesnt response... what should I do..?
[latest.log](https://github.com/unhappychoice/ReplayMod/files/6790650/latest.log)
[debug.log](https://github.com/unhappychoice/ReplayMod/files/6790651/debug.log)
![제목 없음](https://user-images.githubusercontent.com/79464981/125065045-4f2a2d80-e0ec-11eb-9ba5-49d50d3a1df5.png)

**Comment by unhappychoice** [comment]
How much does memory allocated? How is the CPU, memory, disk usage?
The logs says nothing about a problem so I can do nothing

**Comment by CamillaLee** [comment]
I think there is enough memory... 
![제목 없음1](https://user-images.githubusercontent.com/79464981/125067425-3a02ce00-e0ef-11eb-917e-f3fe20a68439.png)

I have allocated 64G to minecraft(from 96G)

**Comment by unhappychoice** [comment]
I think 64G is toooooooooo much and 10G will be more performant.
Anyway, there is no clue so I can do nothing

**Comment by unhappychoice** [comment]
- ffmpeg
- 4K resolution

may cause the problem
