### ISSUE TITLE
Replay Mod is incompatible with forge versions 3.1.61 to 3.2.1

### ISSUE THREAD

**Issue by TYPyz** [unhappychoice/ReplayMod#21]
By creating a modpack with nothing but forge and the ReplayMod the modpack crashes on startup.
It would be nice if you made it compatible with forge 3.2.0 with a new update because some mods like Ars Nouveau are no longer compatible with the forge version lower than 3.1.61.
[crash-2021-07-26_13.57.39-client.txt](https://github.com/unhappychoice/ReplayMod/files/6878115/crash-2021-07-26_13.57.39-client.txt)

**Comment by TechnoFoxed** [comment]
what on earth is version 3.1.61? that is only avalible in version 1.2??

**Comment by TYPyz** [comment]
> what on earth is version 3.1.61? that is only avalible in version 1.2??

Keep reading my comment until you understand where you are wrong

**Comment by TYPyz** [comment]
> what on earth is version 3.1.61? that is only avalible in version 1.2??

I'm talking about forge...
https://files.minecraftforge.net/net/minecraftforge/forge/index_1.16.5.html
