### ISSUE TITLE
replay viewer visual lag

### ISSUE THREAD

**Issue by CamillaLee** [unhappychoice/ReplayMod#3]
Can somebody help me..?  I'm using replay mod in mc1.16.5 with optifine, and I have some problems using replay mod since the replay viewer cannot load some modded textures properly... when I'm playing MC(to record new video) it looks fine in-game but when I try to see the recorded video with replay viewer, some block textures from MODs suddenly mixed up and doesn't look like what really is... I don't know how to fix this please help me...

by the way I really appreciate you for making this mod...

- [ ] 
[latest.log](https://github.com/unhappychoice/ReplayMod/files/6602766/latest.log)

**Comment by CJStanleyWinter** [comment]
Having this exact same issue, so glad it's not just me.

Please fix, thank youuu <3

**Comment by unhappychoice** [comment]
Please tell me the modpack or all the mods installed

**Comment by CamillaLee** [comment]
Here's my Mod list

- environmental-1.16.5-1.0.0.jar
- FpsReducer-mc1.16.5-1.19.jar
- .jar
- .jar
- .jar
- .jar
- .jar
- .jar
- .jar
- .jar
- .jar

**Comment by unhappychoice** [comment]
How about installing Pam's HarvestCraft 2 Crops mod.
The `latest.log` said it's missing and you're not using the mod.

**Comment by unhappychoice** [comment]
It seems to be same to #2
