### ISSUE TITLE
I am not able to use replay mod for multiplayer servers as it works fine for singleplayer

### ISSUE THREAD

**Issue by ss751** [unhappychoice/ReplayMod#4]
[latest.log](https://github.com/unhappychoice/ReplayMod/files/6605976/latest.log)

**Comment by unhappychoice** [comment]
I don't understand `works fine`.
Describe the actual problem precisely.

**Comment by ss751** [comment]
> I don't understand `works fine`.
> Describe the actual problem precisely.

When i recorded in singleplayer then it records but for multiplayer servers it doesnt records

**Comment by ss751** [comment]
When i record in singleplayer it records normally but for multiplayer it doesnt record even doesnt show start record  option

**Comment by ss751** [comment]
![Mod loaded](https://user-images.githubusercontent.com/85472007/120964398-e49a7080-c780-11eb-8589-a4b6770f63a8.PNG)
![Record server is on](https://user-images.githubusercontent.com/85472007/120964414-e8c68e00-c780-11eb-84f4-f3853443476b.PNG)
![Works for singleplayer](https://user-images.githubusercontent.com/85472007/120964419-e9f7bb00-c780-11eb-804d-9e730616bd00.PNG)
![But still not recording](https://user-images.githubusercontent.com/85472007/120964420-ebc17e80-c780-11eb-884b-cd73b9554a7a.PNG)

**Comment by unhappychoice** [comment]
Fixed by: https://github.com/unhappychoice/ReplayMod/commit/3e2118b20e74317ea3653992082807999e98f1be
Released in: https://github.com/unhappychoice/ReplayMod/releases/tag/1.0.0-beta3
