### ISSUE TITLE
Incorrect Blocks again

### ISSUE THREAD

**Issue by CJStanleyWinter** [unhappychoice/ReplayMod#6]
Ok, so I thought everything was fixed.
There shouldn't be any mod conflicts this time, as no mods have been removed on this new world.

But some quark blocks are still rendering incorrectly

![Base Profile Screenshot 2021 06 12 - 19 37 04 94](https://user-images.githubusercontent.com/42320511/121786157-072fed80-cbb6-11eb-8888-8e884648389a.png)

![Base Profile Screenshot 2021 06 12 - 19 38 06 60](https://user-images.githubusercontent.com/42320511/121786167-1151ec00-cbb6-11eb-8f78-a7f822a2a554.png)

[latest.log](https://github.com/unhappychoice/ReplayMod/files/6642730/latest.log)

**Comment by unhappychoice** [comment]
This https://github.com/unhappychoice/ReplayMod/issues/1#issuecomment-830566561

**Comment by unhappychoice** [comment]
May be fixed by https://github.com/unhappychoice/ReplayMod/releases/tag/1.0.0
