### ISSUE TITLE
Incorrect Create Block Renders

### ISSUE THREAD

**Issue by boyenn** [unhappychoice/ReplayMod#9]
I've read through https://github.com/unhappychoice/ReplayMod/issues/2 , but I seem to get different errors resulting in the same problem ( My Create blocks are being rendered as other seemingly random blocks ).

As seen in the log, I don't get any of the "Found a missing id from the world" like OP had there.

Is this to do with Storage Drawers, due to the line 
`Netty Client IO #0/ERROR] [net.minecraftforge.fml.network.NetworkRegistry/NETREGISTRY]: Channels [storagedrawers:main_channel,create:network] rejected vanilla connections`  ?

Thank you so much for making this fork btw. Have you got any donation platforms ?
[latest.log](https://github.com/unhappychoice/ReplayMod/files/6688225/latest.log)

**Comment by unhappychoice** [comment]
Needs investigation

**Comment by unhappychoice** [comment]
> Thank you so much for making this fork btw. Have you got any donation platforms ?

Here is https://patreon.com/leocraft
But I'm not actively using this.
Of course you decide whether you donate or not and I'll be just happy if you do that

**Comment by unhappychoice** [comment]
May be fixed by https://github.com/unhappychoice/ReplayMod/releases/tag/1.0.0
